# ARTIFICIAL NEURAL NETWORK ASSIGNMENT-8

## _ABHISHEK_SUTAR

 8. Create a Neural network architecture from scratch in Python and use it to do multi-class classification on any data.
 Parameters to be considered while creating the neural network from scratch are specified as:
 (1) No of hidden layers : 1 or more
 (2) No. of neurons in hidden layer: 100
 (3) Non-linearity in the layer : Relu
 (4) Use more than 1 neuron in the output layer. Use a suitable threshold value

In [3]:
import numpy as np

In [4]:

def relu(x):
    return np.maximum(0, x)

# def forward(X, W1, W2):
#     z1 = np.dot(X, W1)
#     a1 = relu(z1)
#     z2 = np.dot(a1, W2)
#     return z2

# threshold = 0.5
# z2 = forward(X_test, W1, W2)
# predictions = (z2 > threshold).astype(int)


def softmax(x):
    exp_x = np.exp(x)
    return exp_x / np.sum(exp_x, axis=1, keepdims=True)


def forward(X, W1, W2):
    z1 = np.dot(X, W1)
    a1 = relu(z1)
    z2 = np.dot(a1, W2)
    y_hat = relu(z2)
    return y_hat, a1, z1

def compute_loss(y_hat, y):
    loss = -np.mean(y * np.log(y_hat))
    return loss



def backprop(X, y, y_hat, a1, z1, W1, W2):
    m = X.shape[0]
    dL_dz2 = (y_hat - y) / m
    dL_dW2 = np.dot(a1.T, dL_dz2)
    dL_da1 = np.dot(dL_dz2, W2.T)
    dL_dz1 = dL_da1 * (z1 > 0)
    dL_dW1 = np.dot(X.T, dL_dz1)
    return dL_dW1, dL_dW2

In [5]:
input_size = 10
hidden_size = 100
output_size = 3
learning_rate = 0.01

W1 = np.random.randn(input_size, hidden_size)
W2 = np.random.randn(hidden_size, output_size)
# For example, if you have a dataset with 1000 samples, where each sample has 10 features and there are 3 classes, you could define X_train and y_train as follows:

X_train = np.random.randn(1000, 10)
y_train = np.random.randint(0, 3, size=(1000,))
# In this example, X_train is a matrix with shape (1000, 10) where each row represents a sample and each column represents a feature. y_train is a vector with shape (1000,) where each element represents the class label of the corresponding sample in X_train.
num_classes = 3
y_train_one_hot = np.eye(num_classes)[y_train]
print(y_train_one_hot)
for epoch in range(1000):
    print("iteration:",epoch)
    print('Input data:')
    print(X_train)
    y_hat, a1, z1 = forward(X_train, W1, W2)
    print('Predicted probabilities:')
    print(y_hat)
    loss = compute_loss(y_hat, y_train_one_hot)
    if epoch % 100 == 0:
        print(f'Epoch: {epoch}, Loss: {loss}')
    dL_dW1, dL_dW2 = backprop(X_train, y_train_one_hot, y_hat, a1, z1, W1, W2)
    W1 -= learning_rate * dL_dW1
    W2 -= learning_rate * dL_dW2
    predictions = np.argmax(y_hat, axis=1)
    print('Predicted class labels:')
    print(predictions)


[[1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 ...
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
iteration: 0
Input data:
[[ 0.9170156   1.31066577 -1.27839547 ... -0.35655265 -1.89080087
   0.85207278]
 [-0.36518273 -0.51051829  0.00359489 ...  0.27255918 -0.24941011
   0.51684876]
 [ 0.49952213 -0.13179571  1.75928321 ...  1.0543794   1.54946889
   0.64856575]
 ...
 [-2.63522956 -1.20921026 -0.44188188 ...  0.77642002 -0.06435734
   0.92407647]
 [-0.22998788  0.27597897 -0.5909827  ...  0.4094908   1.36286321
   0.55894241]
 [ 0.95067824  0.03150885  0.49247671 ...  1.72015304  1.03256282
   1.31378764]]
Predicted probabilities:
[[ 0.          0.         21.72921208]
 [ 0.          0.          5.23155788]
 [ 0.         19.9732926   0.        ]
 ...
 [ 0.          0.          0.        ]
 [ 0.          0.         12.47322134]
 [ 1.62686538  3.0063813   0.        ]]
Epoch: 0, Loss: nan
Predicted class labels:
[2 2 1 1 2 2 0 2 0 1 1 2 1 0 2 2 2 0 0 0 2 1 2 0 1 1 2 2 2 2 2 2 2 2 2 2 0
 2 2 1 2 0 1 0 0 0 0 

C:\Users\shiva\AppData\Local\Temp\ipykernel_264\1243695018.py:28: RuntimeWarning: divide by zero encountered in log
  loss = -np.mean(y * np.log(y_hat))
C:\Users\shiva\AppData\Local\Temp\ipykernel_264\1243695018.py:28: RuntimeWarning: invalid value encountered in multiply
  loss = -np.mean(y * np.log(y_hat))


Predicted class labels:
[2 0 0 0 0 0 0 0 0 1 1 2 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 2 2 0 0 0 0 0 0
 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 2 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0
 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 2 0 2 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0
 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 2 0 0 2 0 0 0 0 0 2 0 0 2
 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1
 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 2 0 0 0 0 0 2 0 0 0 2 0 0 0 1 0 0 0 0 0 2
 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 2 0 0 2 0 2 0 0 0 0 1 0 0 2 0 0 0 0 0
 0 0 2 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 1 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 2 0 0 0 0 1 0 0 1 1 0 0 0 1 1 0 0 0 0 0 1 1 2 0 0 2 0 0 0 0
 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 2 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 2 0 0 0
 0 0 0 0 1 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0
 