## Artificial Neural Network Assignment-3

## _Abhishek_Sutar
### 3. Write a Python Program using Perceptron Neural Network to recognise even and odd numbers.Given numbers are in ASCII form 0 to 9

In [2]:
import numpy as np

In [3]:
# # Generate training data
# X = np.array([[int(i) for i in list('{0:08b}'.format(x))] for x in range(256)])
# y = np.array([x % 2 for x in range(256)]).reshape(-1, 1)

# # Initialize weights
# np.random.seed(1)
# weights = 2 * np.random.random((8, 1)) - 1

# # Set learning rate
# learning_rate = 2

# # Train the perceptron
# for epoch in range(100):
#     # Forward propagation
#     layer0 = X
#     layer1 = np.dot(layer0, weights)

#     # Calculate error
#     layer1_error = y - layer1

#     # Update weights
#     weights += learning_rate * np.dot(layer0.T, layer1_error)

# # Classify input
# def classify(x):
#     binary_input = np.array([int(i) for i in list('{0:08b}'.format(x))])
#     output = np.dot(binary_input, weights)
#     if round(output[0]) == 0:
#         return "even"
#     else:
#         return "odd"

# # Test classification
# print(classify(7)) # odd
# print(classify(8)) # even

In [4]:
def sigmoid(x,der=False):
    if der==True:
        return sigmoid(x)*(1-sigmoid(x))
    return 1/(1+np.exp(-x))

# Generate training data
X = np.array([[int(i) for i in list('{0:08b}'.format(x))] for x in range(256)])
y = np.array([x % 2 for x in range(256)]).reshape(-1, 1)
print(X)
print(y)


# Initialize weights
np.random.seed(1)
weights = 2 * np.random.random((8, 1)) - 1

# Train the neural network
for epoch in range(10000):
    # Forward propagation
    layer0 = X
    layer1 = sigmoid(np.dot(layer0, weights),der=False)

    # Calculate error
    layer1_error = y - layer1

    # Backpropagation
    layer1_delta = layer1_error * sigmoid(layer1,der=True)

    # Update weights
    weights += np.dot(layer0.T, layer1_delta)





# # Test classification
# print(classify(9)) # odd
# print(classify(2)) # even


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 1 0]
 ...
 [1 1 1 ... 1 0 1]
 [1 1 1 ... 1 1 0]
 [1 1 1 ... 1 1 1]]
[[0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]


In [5]:

# Test the neural network
test_input = np.array([[int(i) for i in list('{0:08b}'.format(x))] for x in range(256)])

print("test input:",test_input)
test_output = sigmoid(np.dot(test_input, weights),der=False)
print("test output:",test_output)
# Evaluate the model
accuracy = np.mean(np.round(test_output) == y)
print("\nAccuracy: %.2f%%" % (accuracy*100))



test input: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 1 0]
 ...
 [1 1 1 ... 1 0 1]
 [1 1 1 ... 1 1 0]
 [1 1 1 ... 1 1 1]]
test output: [[5.00000000e-01]
 [1.00000000e+00]
 [3.13275633e-03]
 [1.00000000e+00]
 [3.13275633e-03]
 [1.00000000e+00]
 [9.87584560e-06]
 [1.00000000e+00]
 [3.13275633e-03]
 [1.00000000e+00]
 [9.87584560e-06]
 [1.00000000e+00]
 [9.87584560e-06]
 [1.00000000e+00]
 [3.10361511e-08]
 [1.00000000e+00]
 [3.13275633e-03]
 [1.00000000e+00]
 [9.87584560e-06]
 [1.00000000e+00]
 [9.87584560e-06]
 [1.00000000e+00]
 [3.10361511e-08]
 [1.00000000e+00]
 [9.87584560e-06]
 [1.00000000e+00]
 [3.10361511e-08]
 [1.00000000e+00]
 [3.10361511e-08]
 [1.00000000e+00]
 [9.75342528e-11]
 [1.00000000e+00]
 [3.13275633e-03]
 [1.00000000e+00]
 [9.87584560e-06]
 [1.00000000e+00]
 [9.87584560e-06]
 [1.00000000e+00]
 [3.10361511e-08]
 [1.00000000e+00]
 [9.87584560e-06]
 [1.00000000e+00]
 [3.10361511e-08]
 [1.00000000e+00]
 [3.10361511e-08]
 [1.00000000e+00]
 [9.75342528e-11]
 [1.00000

In [6]:
# Classify input
def classify(x):
    binary_input = np.array([int(i) for i in list('{0:08b}'.format(x))])
    print("binary input:",binary_input)
    output = sigmoid(np.dot(binary_input, weights),der=False)
    print("output",output)
    if round(output[0]) == 0:
        return "even"
    else:
        return "odd"

In [7]:
classify(25)

binary input: [0 0 0 1 1 0 0 1]
output [1.]


'odd'

In [8]:
classify(17)

binary input: [0 0 0 1 0 0 0 1]
output [1.]


'odd'

In [9]:
classify(2)

binary input: [0 0 0 0 0 0 1 0]
output [0.00313276]


'even'

In [10]:
classify(8)

binary input: [0 0 0 0 1 0 0 0]
output [0.00313276]


'even'

In [11]:
classify(9)

binary input: [0 0 0 0 1 0 0 1]
output [1.]


'odd'