In [1]:
import numpy as np
#input pattern
x1=np.array([1,-1,1,1]).reshape(4,1)
x2=np.array([-1,-1,1,1]).reshape(4,1)
x3=np.array([1,1,-1,1]).reshape(4,1)
x4=np.array([-1,1,-1,1]).reshape(4,1)

#Target Pattern

y1=np.array([1,1,1]).reshape(3,1)
y2=np.array([1,0,1]).reshape(3,1)
y3=np.array([0,1,1]).reshape(3,1)
y4=np.array([1,1,0]).reshape(3,1)

#Calculate weight matrix
inputSet=np.concatenate((x1,x2,x3,x4), axis=1)
targetSet=np.concatenate((y1.T,y2.T,y3.T,y4.T),axis=0)
print("\n Weight matrix:")
weight=np.dot(inputSet,targetSet)
print(weight)


#Testing phase for the input pattern

def testInputs(x,weight):
    y=np.dot(weight.T,x)
    y[y>1]=1
    y[y<1]=0
    return np.array(y)

print("\output of the input pattern 1")
print(testInputs(x1,weight))
print("\output of the input pattern 2")
print(testInputs(x2,weight))
print("\output of the input pattern 3")
print(testInputs(x3,weight))
print("\output of the input pattern 4")
print(testInputs(x4,weight))

#Testing phase for the target patterns

# def testTarget(y,weight):
#     x=np.dot(weight,y)
#     x[x>1]=1
#     x[x<1]=0
#     return np.array(x)

# print("\output of the input pattern 1")
# print(testTarget(y1,weight))
# print("\output of the input pattern 2")
# print(testTarget(y2,weight))
# print("\output of the input pattern 3")
# print(testTarget(y3,weight))
# print("\output of the input pattern 4")
# print(testTarget(y4,weight))



 Weight matrix:
[[-1  1  1]
 [-1  1 -1]
 [ 1 -1  1]
 [ 3  3  3]]
\output of the input pattern 1
[[1]
 [1]
 [1]]
\output of the input pattern 2
[[1]
 [0]
 [1]]
\output of the input pattern 3
[[0]
 [1]
 [1]]
\output of the input pattern 4
[[1]
 [1]
 [0]]


In [18]:
a = [[1,2],[3,4]]
b = [[1,1],[1,1],[1,1]]

In [19]:
a = np.array(a)
b = np.array(b)
b.T


array([[1, 1, 1],
       [1, 1, 1]])

In [21]:
np.dot(b,a)

array([[4, 6],
       [4, 6],
       [4, 6]])